### ISSUE TITLE
Can not see any difference

### ISSUE THREAD

**Issue by DanielRuf** [FriendsOfShopware/FroshPerformance#7] opened 2019-01-06 18:14 UTC
Actually I see no real difference after the installation.
The HTML looks the same.
Can you show a few before / after results (also from startpages of a demoshop)?

**Comment by stefanpoensgen** [comment] 2019-01-06 18:28
**before**
![before](https://i.imgur.com/XaSsZXo.png)

**after**
![after](https://i.imgur.com/dkJounZ.png)

**Comment by shyim** [comment] 2019-01-06 18:29
Is the plugin active and is the option enabled in the config?
Maybe config cache clearing :)

**Comment by DanielRuf** [comment] 2019-01-06 18:33
> Is the plugin active and is the option enabled in the config?
> Maybe config cache clearing :)

Yes and yes.
Was the question by the plugin manager after the install not sufficient whichg asked me if I want to clear the caches. I clicked `yes` and saw no difference.

In contrast, the webp plugin changes were directly applied.

**Comment by DanielRuf** [comment] 2019-01-06 18:34
@stefanpoensgen Unfortunately it still looks like the **before**  part on our website.

**Comment by DanielRuf** [comment] 2019-01-06 18:34
> Is the plugin active and is the option enabled in the config?

It was by default.

**Comment by shyim** [comment] 2019-01-06 19:28
I installed this plugin and webp together and cannot reproduce that

**Comment by DanielRuf** [comment] 2019-01-06 19:59
Mh, maybe we'll further test and debug it but we'll probably wait for 5.6 and #2 solutions as this would affect all subshops.

**Comment by shyim** [comment] 2019-01-18 13:22
I will close it then, cause we cannot reproduce that :)

**Closed as completed by shyim** 2019-01-18 13:22 UTC
Labels: question
